# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

# Define how much memory your computer has in GB (e.g. 8, 16)
# Larger nodes will be created if you have more.
RAM_SIZE = 32

# Define how many CPU cores you have.
# More powerful workers will be created if you have more
CPU_CORES = 8

# Internal network prefix for the VM network
# See the documentation before changing this
IP_NW = "192.168.100."

# Calculate resource amounts
# based on RAM/CPU
ram_selector = (RAM_SIZE / 4) * 4
if ram_selector < 8
  raise "Insufficient memory #{RAM_SIZE}GB. min 8GB"
end
RESOURCES = {
  "control" => {
    1 => {
      # controlplane01 bigger since it may run e2e tests.
      "ram" => [ram_selector * 128, 4096].min(),
      "cpu" => CPU_CORES >= 12 ? 4 : 2,
    },
    2 => {
      # All additional masters get this
      "ram" => [ram_selector * 128, 4096].min(),
      "cpu" => CPU_CORES > 8 ? 2 : 1,
    },
    3 => {
      # All additional masters get this
      "ram" => [ram_selector * 128, 4096].min(),
      "cpu" => CPU_CORES > 8 ? 2 : 1,
    },
  },
  "worker" => {
    "ram" => [ram_selector * 128, 8192].max(),
    "cpu" => CPU_CORES
  },
}

# Runs provisioning steps that are required by masters and workers
def provision_kubernetes_node(node)
  # Set up kernel parameters, modules and tuning
  node.vm.provision "setup-kernel", :type => "shell", :path => "fedora/setup-kernel.sh"
  # Set up fedora
  node.vm.provision "setup-fedora", :type => "shell", :path => "fedora/setup-fedora.sh"
  # Set up DNS
  node.vm.provision "setup-hosts", :type => "shell", :path => "fedora/setup-hosts.sh"
  # Install cert verification script
  node.vm.provision "shell", inline: "chmod +x /vagrant/cert_verify.sh && ln -s /vagrant/cert_verify.sh /home/vagrant/cert_verify.sh"
  # Provide Kubernetes Config
  node.vm.provision "shell", inline: "ln -s /vagrant/configs /home/vagrant/configs"
  node.vm.provision "shell", inline: "ln -s /vagrant/downloads.txt /home/vagrant/downloads.txt"
  node.vm.provision "shell", inline: "ln -s /vagrant/infra /home/vagrant/infra"
  node.vm.provision "shell", inline: "ln -s /vagrant/liferay /home/vagrant/liferay"
  node.vm.provision "shell", inline: "ln -s /vagrant/templates /home/vagrant/templates"
end

# Define the number of master and worker nodes. You should not change this
NUM_CONTROL_NODES = 3
NUM_WORKER_NODE = 2

# Host address start points
MASTER_IP_START = 10
NODE_IP_START = 20
LB_IP_START = 30

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "base"
  config.vm.box = "fedora/41-cloud-base"
  config.vm.boot_timeout = 900

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Provision Control Nodes
  (1..NUM_CONTROL_NODES).each do |i|
    config.vm.define "controlplane0#{i}" do |node|
      IPADDR = IP_NW + "#{MASTER_IP_START + i}"
      # Name shown in the GUI
      node.vm.provider "libvirt" do |libvirt|
        libvirt.cpus = RESOURCES["control"][i > 2 ? 2 : i]["cpu"]
        libvirt.default_prefix = "kubernetes-ha-"
        libvirt.driver = "kvm"
        libvirt.machine_virtual_size = 50
        libvirt.memory = RESOURCES["control"][i > 2 ? 2 : i]["ram"]
        libvirt.uri = 'qemu:///system'
      end
      node.vm.hostname = "controlplane0#{i}"
      node.vm.network :private_network, ip: IP_NW + "#{MASTER_IP_START + i}"
      node.vm.synced_folder "./", "/vagrant", type: "sshfs"
      node.vm.provision "setup-networking", :type => "shell", :path => "fedora/setup-networking.sh", env: {"IPADDR" => IPADDR}
      provision_kubernetes_node node
      if i == 1
        # Install (opinionated) configs for vim and tmux on controlplane01. These used by the author for CKA exam.
        node.vm.provision "file", source: "./fedora/tmux.conf", destination: "$HOME/.tmux.conf"
        node.vm.provision "file", source: "./fedora/vimrc", destination: "$HOME/.vimrc"
      end
    end
  end

  # Provision Load Balancer Node
  config.vm.define "loadbalancer" do |node|
    IPADDR = IP_NW + "#{LB_IP_START}"
    node.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 1
      libvirt.default_prefix = "kubernetes-ha-"
      libvirt.driver = "kvm"
      libvirt.machine_virtual_size = 50
      libvirt.memory = 1024
      libvirt.uri = 'qemu:///system'
    end
    node.vm.hostname = "loadbalancer"
    node.vm.network :private_network, ip: IP_NW + "#{LB_IP_START}"
    node.vm.synced_folder "./", "/vagrant", type: "sshfs"
    node.vm.provision "setup-networking", :type => "shell", :path => "fedora/setup-networking.sh", env: {"IPADDR" => IPADDR}
    # Set up fedora
    node.vm.provision "setup-fedora", :type => "shell", :path => "fedora/setup-fedora.sh"
    node.vm.provision "setup-hosts", :type => "shell", :path => "fedora/setup-hosts.sh"
  end

  # Provision Worker Nodes
  (1..NUM_WORKER_NODE).each do |i|
    config.vm.define "node0#{i}" do |node|
      IPADDR = IP_NW + "#{NODE_IP_START + i}"
      node.vm.provider "libvirt" do |libvirt|
        libvirt.cpus = RESOURCES["worker"]["cpu"]
        libvirt.default_prefix = "kubernetes-ha-"
        libvirt.driver = "kvm"
        libvirt.machine_virtual_size = 50
        libvirt.memory = RESOURCES["worker"]["ram"]
        libvirt.uri = 'qemu:///system'

      end
      node.vm.hostname = "node0#{i}"
      node.vm.network :private_network, ip: IP_NW + "#{NODE_IP_START + i}"
      node.vm.synced_folder "./", "/vagrant", type: "sshfs"
      node.vm.provision "setup-networking", :type => "shell", :path => "fedora/setup-networking.sh", env: {"IPADDR" => IPADDR}
      provision_kubernetes_node node
    end
  end
end
